
// import { SearchProvider } from "@/app/context/SearchContext"; // Import the SearchProvider

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import HideLayout from "./hide-layout";
import Sale from "./components/layout/salePoster";
import Footer from "./components/layout/footer";
import { CartProvider } from "@/app/context/CartContext";
import { WishlistProvider } from "./context/WishlistContext";
import { ClerkProvider } from "@clerk/nextjs";
import { SearchProvider } from "./context/SearchContext"; 

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ClerkProvider>
      <html lang="eu">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased max-w-screen-2xl mx-auto`}
        >
          <SearchProvider>
          <CartProvider>
            <WishlistProvider>
              <SearchProvider>   {/* Wrap with SearchProvider */}
                {/* <Header /> Include the Header component here */}
                <Sale />
                <HideLayout />
                {children}
                <Footer />
              </SearchProvider>
            </WishlistProvider>
          </CartProvider>
          </SearchProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}